
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types
    - camel_case_types
    - empty_constructor_bodies
    - prefer_const_constructors
    - prefer_final_fields
    - prefer_const_literals_to_create_immutables
    - prefer_equal_for_default_values
    - prefer_is_not_empty
    - sort_child_properties_last
    - unnecessary_new
