import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;

class CreateVoucherScreen extends StatefulWidget {
  final String ipAddress;
  final String token;

  const CreateVoucherScreen({super.key, required this.ipAddress, required this.token});

  @override
  State<CreateVoucherScreen> createState() => _CreateVoucherScreenState();
}

class _CreateVoucherScreenState extends State<CreateVoucherScreen> {
  final _formKey = GlobalKey<FormState>();
  int _amount = 1;
  int _quota = 1; // in hours
  int _expiration = 24; // in hours
  bool _isLoading = false;
  String _status = '';

  Future<void> _createVouchers() async {
    if (_formKey.currentState!.validate()) {
      _formKey.currentState!.save();
      setState(() {
        _isLoading = true;
        _status = 'Creating vouchers...';
      });

      final Uri url = Uri.parse('https://${widget.ipAddress}/api/v2/hotspot/vouchers?token=${widget.token}');

      try {
        final response = await http.post(
          url,
          headers: {'Content-Type': 'application/json; charset=UTF-8'},
          body: jsonEncode(<String, dynamic>{
            'amount': _amount,
            'quota': _quota * 60, // Convert hours to minutes
            'expire_time': _expiration,
            'reusable': 1, // 1 for single use
            'download_limit': 0, // 0 for unlimited
            'upload_limit': 0, // 0 for unlimited
            'rate_limit_unit': 'mbps',
            'note': 'Generated by Flutter App'
          }),
        );

        final responseBody = jsonDecode(response.body);

        if (response.statusCode == 200 && responseBody['errorCode'] == 0) {
          setState(() {
            _status = 'Vouchers created successfully!';
            _isLoading = false;
          });
          if (!mounted) return;
          Navigator.pop(context, true); // Return true to indicate success
        } else {
          setState(() {
            _status = 'Failed to create vouchers: ${responseBody['msg'] ?? 'Unknown error'}';
            _isLoading = false;
          });
        }
      } catch (e) {
        setState(() {
          _status = 'Error: ${e.toString()}';
          _isLoading = false;
        });
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Create Vouchers'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Form(
          key: _formKey,
          child: Column(
            children: [
              TextFormField(
                decoration: const InputDecoration(labelText: 'Number of Vouchers'),
                keyboardType: TextInputType.number,
                initialValue: _amount.toString(),
                validator: (value) {
                  if (value == null || int.tryParse(value) == null) {
                    return 'Please enter a valid number';
                  }
                  return null;
                },
                onSaved: (value) => _amount = int.parse(value!),
              ),
              TextFormField(
                decoration: const InputDecoration(labelText: 'Quota (in hours)'),
                keyboardType: TextInputType.number,
                initialValue: _quota.toString(),
                validator: (value) {
                  if (value == null || int.tryParse(value) == null) {
                    return 'Please enter a valid number';
                  }
                  return null;
                },
                onSaved: (value) => _quota = int.parse(value!),
              ),
              TextFormField(
                decoration: const InputDecoration(labelText: 'Expiration (in hours)'),
                keyboardType: TextInputType.number,
                initialValue: _expiration.toString(),
                validator: (value) {
                  if (value == null || int.tryParse(value) == null) {
                    return 'Please enter a valid number';
                  }
                  return null;
                },
                onSaved: (value) => _expiration = int.parse(value!),
              ),
              const SizedBox(height: 20),
              ElevatedButton(
                onPressed: _isLoading ? null : _createVouchers,
                child: const Text('Create'),
              ),
              const SizedBox(height: 20),
              if (_isLoading)
                const CircularProgressIndicator(),
              if (_status.isNotEmpty)
                Text(_status, style: const TextStyle(color: Colors.red)),
            ],
          ),
        ),
      ),
    );
  }
}
