// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_Qy9ssGXcAOH8oM6h8HDBDmhP9ALowZ4',
    appId: '1:878377640142:web:094848249c7b8f6686309f',
    messagingSenderId: '878377640142',
    projectId: 'mangalamwifi',
    authDomain: 'mangalamwifi.firebaseapp.com',
    storageBucket: 'mangalamwifi.firebasestorage.app',
    measurementId: 'G-XVTBRCRB8Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7nl4cMbrI_GlfMWzameZMcLnr0W8G4bE',
    appId: '1:878377640142:android:98e72cc13bac501086309f',
    messagingSenderId: '878377640142',
    projectId: 'mangalamwifi',
    storageBucket: 'mangalamwifi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqCMTq1nGDzVhAcuoztW6OlzrACfebJf0',
    appId: '1:878377640142:ios:8e4276bf2306bf9a86309f',
    messagingSenderId: '878377640142',
    projectId: 'mangalamwifi',
    storageBucket: 'mangalamwifi.firebasestorage.app',
    iosBundleId: 'com.example.mangalamWifiZone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqCMTq1nGDzVhAcuoztW6OlzrACfebJf0',
    appId: '1:878377640142:ios:8e4276bf2306bf9a86309f',
    messagingSenderId: '878377640142',
    projectId: 'mangalamwifi',
    storageBucket: 'mangalamwifi.firebasestorage.app',
    iosBundleId: 'com.example.mangalamWifiZone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_Qy9ssGXcAOH8oM6h8HDBDmhP9ALowZ4',
    appId: '1:878377640142:web:5cbed10c6a548d3986309f',
    messagingSenderId: '878377640142',
    projectId: 'mangalamwifi',
    authDomain: 'mangalamwifi.firebaseapp.com',
    storageBucket: 'mangalamwifi.firebasestorage.app',
    measurementId: 'G-0WMRBHDGEV',
  );
}
